# Generated by Django 5.2.5 on 2025-08-22 02:40

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_role_userprofile_address_vendorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='uuid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=12, max_length=50, prefix=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=12, max_length=50, prefix=''),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='uuid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=12, max_length=50, prefix=''),
        ),
    ]
