# Generated by Django 5.2.5 on 2025-08-22 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_address_uuid_userprofile_uuid_vendorprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'BUYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
