# Generated by Django 5.2.5 on 2025-08-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['profile', 'address_type'], name='userauths_a_profile_885ed7_idx'),
        ),
    ]
