# Generated by Django 5.2.5 on 2025-08-22 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_productimage_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='store.productvariation'),
        ),
    ]
