# Generated by Django 5.2.5 on 2025-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_category_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
