# Generated by Django 5.2.5 on 2025-08-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productvariation_is_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariation',
            options={'ordering': ['sale_price']},
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='price',
            new_name='regular_price',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='show_regular_price',
            field=models.BooleanField(default=True),
        ),
    ]
