# Generated by Django 5.2.5 on 2025-08-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_productvariation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='show_regular_price',
            field=models.BooleanField(default=False),
        ),
    ]
