# Generated by Django 5.2.5 on 2025-08-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productvariation_show_regular_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='label',
            field=models.CharField(choices=[('Hot', 'Hot'), ('New', 'New'), ('Sale', 'Sale'), ('Bestseller', 'Bestseller'), ('Limited', 'Limited'), ('Featured', 'Featured'), ('Exclusive', 'Exclusive'), ('Coming Soon', 'Coming Soon'), ('Back in Stock', 'Back in Stock'), ('Trending', 'Trending'), ('Clearance', 'Clearance'), ('Popular', 'Popular'), ('Gift', 'Gift')], default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='show_discount',
            field=models.BooleanField(default=False),
        ),
    ]
