# Generated by Django 5.2.5 on 2025-08-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productvariation_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='show_discount',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='show_discount_type',
            field=models.CharField(choices=[('price', 'Show Discount in Price'), ('percentage', 'Show Discount in Percentage'), ('none', 'Do Not Show Discount')], default='none', max_length=100),
        ),
    ]
