# Generated by Django 5.2.5 on 2025-08-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_productvariation_show_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='deal_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='deal_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='deal_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
