# Generated by Django 5.2.5 on 2025-08-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productvariation_deal_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
