# Generated by Django 5.2.5 on 2025-08-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productvariation_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='trending',
        ),
    ]
