# Generated by Django 5.2.5 on 2025-08-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_productvariation_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Height in CM', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='length',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Length in CM', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Weight in KG', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='width',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Width in CM', max_digits=6),
            preserve_default=False,
        ),
    ]
