# Generated by Django 5.2.5 on 2025-09-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_productvariation_height_productvariation_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
