# Generated by Django 5.2.5 on 2025-10-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_productreview_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
