# Generated by Django 5.2.5 on 2025-10-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_productvariation_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_category',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='show_rating',
            field=models.BooleanField(default=True, help_text='Turn on if you want to show rating on product list page'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_vendor_name',
            field=models.BooleanField(default=True, help_text='Turn on if you want to show vendor store name on product list page'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='show_label',
            field=models.BooleanField(default=True),
        ),
    ]
