# Generated by Django 5.2.5 on 2025-10-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_show_category_product_show_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
