# Generated by Django 5.2.5 on 2025-09-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('store', '0019_productvariation_height_productvariation_length_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product')},
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product_variation',
        ),
    ]
