# Generated by Django 5.2.5 on 2025-08-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cartitem_price'),
        ('store', '0016_productvariation_deal_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_variations_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variation_values',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='store.variationvalue'),
        ),
    ]
