# Generated by Django 5.2.5 on 2025-08-29 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cartitem_selected_variations_json_and_more'),
        ('store', '0019_productvariation_height_productvariation_length_and_more'),
        ('userauths', '0005_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_courier_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_rate_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation_values',
            field=models.ManyToManyField(blank=True, related_name='variations', to='store.variationvalue'),
        ),
        migrations.DeleteModel(
            name='OrderAddress',
        ),
    ]
