# Generated by Django 5.2.5 on 2025-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_address_order_currency_order_item_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
