# Generated by Django 5.2.5 on 2025-09-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_chargeable_weight_kg_order_courier_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_rate_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
