# Generated by Django 5.2.5 on 2025-09-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_coupon_orderitemdiscount_couponredemption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_discount_total',
            new_name='item_discount_total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='items_subtotal_gross',
            new_name='item_total_net',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price_gross',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items_subtotal_net',
        ),
    ]
