# Generated by Django 5.2.5 on 2025-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_items_discount_total_order_item_discount_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='easebuzz_payment_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='easebuzz_txnid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
