# Generated by Django 5.2.5 on 2025-09-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_easebuzz_payment_id_order_easebuzz_txnid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
