# Generated by Django 5.2.5 on 2025-08-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Website', max_length=255)),
                ('site_header', models.CharField(default='My Website Admin', max_length=255)),
                ('site_brand', models.CharField(default='My Website Brand', max_length=255)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('login_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('welcome_text', models.CharField(default='Welcome to My Website', max_length=255)),
                ('footer_text', models.CharField(default='© 2025 My Website', max_length=255)),
                ('singleton', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
