# Generated by Django 5.2.5 on 2025-08-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Our Site', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('cta_text', models.CharField(default='Get Started', max_length=100)),
                ('cta_link', models.URLField(default='/')),
                ('background_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose whether hero background is an image or video', max_length=10)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('background_video', models.FileField(blank=True, help_text='Optional background video (mp4, webm)', null=True, upload_to='hero/')),
                ('overlay_color', models.CharField(default='rgba(0,0,0,0.5)', help_text='Overlay color on top of background', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg_color', models.CharField(default='#ffffff', help_text='Header background color (hex or CSS color)', max_length=20)),
                ('header_text_color', models.CharField(default='#000000', help_text='Header text color (hex or CSS color)', max_length=20)),
                ('singleton', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
