# Generated by Django 5.2.5 on 2025-08-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0002_herosection_themesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='address',
            field=models.CharField(blank=True, help_text='Company address shown in footer/contact', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(blank=True, help_text='Support or sales email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary phone number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='working_hours',
            field=models.CharField(blank=True, help_text='e.g. 10:00 - 18:00, Mon - Sat', max_length=100, null=True),
        ),
    ]
