# Generated by Django 5.2.5 on 2025-08-28 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0003_siteconfiguration_address_siteconfiguration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='e.g. "Twitter", "LinkedIn"', max_length=100)),
                ('icon_class', models.CharField(help_text='FontAwesome or custom CSS class for icon', max_length=100)),
                ('url', models.URLField()),
                ('site_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='addon.siteconfiguration')),
            ],
        ),
    ]
