# Generated by Django 5.2.5 on 2025-08-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0004_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(help_text='FontAwesome: fab fa-youtube', max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
