# Generated by Django 5.2.5 on 2025-08-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0005_alter_sociallink_icon_class_alter_sociallink_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='site_config',
        ),
    ]
