# Generated by Django 5.2.5 on 2025-09-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0007_contactinfo_faqcategory_page_contactmessage_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='page',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_title',
        ),
    ]
