# Generated by Django 5.2.5 on 2025-09-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0008_remove_page_extras_remove_page_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hero_image',
            field=models.FileField(blank=True, null=True, upload_to='image'),
        ),
    ]
