# Generated by Django 5.2.5 on 2025-09-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0009_page_hero_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
        migrations.DeleteModel(
            name='FAQCategory',
        ),
    ]
