# Generated by Django 5.2.5 on 2025-09-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0010_delete_contactinfo_remove_faq_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='currency_abbr',
            field=models.CharField(blank=True, help_text='$', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='currency_symbol',
            field=models.CharField(blank=True, help_text='USD', max_length=255, null=True),
        ),
    ]
