# Generated by Django 5.2.5 on 2025-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0011_siteconfiguration_currency_abbr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='currency_abbr',
            field=models.CharField(blank=True, default='$', help_text='$', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='currency_symbol',
            field=models.CharField(blank=True, default='USD', help_text='USD', max_length=255, null=True),
        ),
    ]
